# @package _global_

wandb: true
project: debug
name: 2ho_render

resume_mode: restart 
load_project: corl-2022
load_tag: latest_17 
wid: 23bfj0ac
load_curri: false

render: true

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false
shared_critic: true

buffer_size: 10000
batch_size: 20
reuse: 0.000001
steps_per_rollout: 100
eval_per_rollout: 1
eval_eps: 16
render_per_eval: 1
eval_only: true
defaults:
  - override /curri: null
  - override /env: 2ho_render
