# @package _global_

wandb: false
project: corl-main
name: main

load_curri: true
resume_mode: load_only
wid: 23bfj0ac
load_project: corl-2022
load_tag: latest_17

render: false

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false

# partial relabel
g_random_relabel_rate: 1.0 
g_random_relabel_bar: 0

# mirror replay
shared_critic: true

buffer_size: 10000
batch_size: 1
reuse: 100
steps_per_rollout: 100
eval_per_rollout: 1

defaults:
  - override /env: 2ho_debug