# @package _global_

wandb: true
project: handover2
name: -shareC+shareA

# load
wid: 3lu8hvt1
load_project: handover1
load_tag: latest_24
resume_mode: restart

render: false

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false

# partial relabel
g_random_relabel_rate: 1.0 
g_random_relabel_bar: 0

# mirror replay
shared_actor: true

# env
defaults:
  - override /env: 2ho

max_collect_steps: !!float 40e6
