# @package _global_

wandb: false
project: corl-main
name: render

resume_mode: load_only 
load_tag: latest_19
wid: 372uaqdq
load_curri: true

render: false

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false
shared_critic: true
shared_actor: true
mask_other_robot_obs: true 

buffer_size: 10000
batch_size: 20
reuse: 0.000001
eval_per_rollout: 1
eval_eps: 100
render_per_eval: 1

defaults:
  - override /env: 2ho_debug