# @package _global_

wandb: true
project: handover8
name: step_comparison

resume_mode: load_only
# load_tag: latest_7 
# wid: 3cn88b0q
load_path: /home/yunfei/projects/isaac_projects/srl/2ho_latest_17.pth
load_curri: true

render: true

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
# act_net: ActorManualPhase
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false
shared_critic: true

buffer_size: 10000
batch_size: 20
reuse: 0.000001
steps_per_rollout: 100
eval_per_rollout: 1
eval_eps: 128

step_comparison: true
warm_up: false
defaults:
  - override /env: 2ho_render