# @package _global_

wandb: true
project: corl-main
name: main

render: false

net_layer: 6
shared_net_layer: 4

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false

# partial relabel
g_random_relabel_rate: 0.0 
g_random_relabel_bar: 0

defaults:
  - override /env: 4ho
  - override /curri: num_14