# used to create the object
name: FrankaCube

# device
sim_device_id: 0
rl_device_id: 0
headless: True 
# set to True if you use camera sensors in the environment
enable_camera_sensors: False 

# env
early_termin_step: 60
early_termin_bar: 0.05
# rew
reward_type: sparse
success_bar: !!float -1e-3
extra_steps: 5
# number
num_cameras: 16
num_envs: 4096 
num_goals: 1
base_steps: 100
max_steps: null
# dim
action_dim: 4
state_dim: null # calculate later
shared_dim: 7 # pos3, vel3, finger1 
per_seperate_dim: 13 # block state
seperate_dim: null
per_goal_dim: 3
goal_dim: null
info_dim: 6 #is_success1, step1, early_termin, traj_idx, traj_len, tleft, achieved_goal3n
# control
control_freq_inv: 1 # TODO check
env_spacing: 1.5
debug_viz: true
damping: 0.05
max_vel: 10.0
max_ik_iter: 10
ik_err: 0.005 # for iteration version of IK
# max_vel: 1.8 # max move 0.05 per step
dof_vel_scale: 1
finger_shift: [0,0,-0.04]
err: 0.05
clip_actions: 1.0
# block
inhand_rate: 0.2
block_size: 0.04 
block_length: 0.04
# robot
num_robots: 1
bound_robot: true
action_shift: [0,0,-0.3,0]
asset:
  assetRoot: 'isaac_assets'
  assetFileNameFranka: 'urdf/franka_description/robots/franka_panda.urdf'
  assetFileNameSphere: 'urdf/sphere.urdf'
# table 
table_size: [1.0, 0.8, 0.4]
table_gap: 0.0
robot_gap: 0.6
robot_y: 0.5
# ee_init_pos: [0.0, 0.0, 0.05]
friction: 0.01
# goal space
goal_space: [0.2, 0.2, 0.1]

# sim:
physics_engine: SIM_PHYSX 
aggregate_mode: 3
dt: 0.02
substeps: 2
up_axis: 'z'
use_gpu_pipeline: true 
gravity: [0.0, 0.0, -9.81]
physx:
  num_threads: 4
  solver_type: 1
  use_gpu: True # set to False to run on CPU
  num_position_iterations: 12 # TODO check this
  num_velocity_iterations: 1
  contact_offset: 0.005
  rest_offset: 0.0
  bounce_threshold_velocity: 0.2
  max_depenetration_velocity: 1000.0
  default_buffer_size_multiplier: 5.0
  max_gpu_contact_pairs: 1048576 # 1024*1024
  num_subscenes: 0
  contact_collection: 0 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (default - all contacts)

task:
  randomize: False