# @package _global_

# load the model and run GUI

resume_mode: load_only
wid: cx426btp
load_project: handover1

defaults:
  - override /env: 1ho_debug

curri: null

steps_per_rollout: 10
eval_eps: 100
eval_per_rollout: 1