# @package _global_

# load the model and run GUI

resume_mode: load_only
wid: 3o6f08ec
project: handover2

defaults:
  - override /env: 1ho_debug

curri: null

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin

steps_per_rollout: 10
eval_eps: 100
eval_per_rollout: 1
updates_per_rollout: 0