# @package _global_

wandb: true
project: handover2
name: sac_default

render: true

agent_name: AgentSAC
act_net: ActorFixSAC
critic_net: CriticTwin
net_type: attn
if_act_target: false

defaults:
  - override /env: 2ho