# @package _global_

wandb: true
resume_mode: restart
load_path: null
load_project: handover2
wid: 1vom6h85 # your wandb wid here
project: handover3
name: resume_from_2ho(fine)

render: true

defaults:
  - override /env: 3ho_fine