# wandb
wandb: false 
project: debug 
name: hello

# seed 
random_seed: 0

# replay
her_rate: 0.8
if_use_per: false
buffer_size: 1000

# env_params
env_name: 'PandaPNP-v0'
env_params: null
env_kwargs:
  num_envs: 4 
  inhand_rate: 1
  num_cameras: 0
reward_scale: 1
extra_info_dim: 0 # extra info get from agent

# network
act_net: ActorFixSAC
critic_net: CriticREDq
net_dim: 128
net_type: deepset
if_act_target: false
if_cri_target: false
gpu_id: 0

# algorithm
agent_name: AgentREDqSAC
max_collect_steps: !!float 1e9
resue: 10
steps_per_rollout: 400
updates_per_rollout: null # calulate with resue
batch_size: 100
gamma: 0.99
lr: 0.00024
soft_update_tau: 0.0039

# eval
eval_per_rollout: 0.1
eval_steps: null # set with steps per rollout
render: true

# save
cwd: results
rollout_per_save: 0.1