# wandb
wandb: true
resume_mode: null
wid: null
project: TD3_debug 
name: pnp_default 

# seed 
random_seed: 0

# replay
her_rate: 0.8
if_use_per: false
buffer_size: 2500000

# env_params
env_name: 'FrankaPNP-v0'
env_params: null
env_kwargs:
  num_envs: 8192 
reward_scale: 1
extra_info_dim: 0 # extra info get from agent

# network
act_net: Actor
critic_net: CriticTwin
net_dim: 128
net_type: deepset
if_act_target: true
if_cri_target: true
gpu_id: 0

# algorithm
agent_name: AgentTD3
max_collect_steps: !!float 1e9
reuse: 10
steps_per_rollout: null
updates_per_rollout: null # calulate with reuse
batch_size: 2048
gamma: 0.98
lr: 0.00024
soft_update_tau: 0.005
explore_noise: 0.2
# TD3
update_freq: 2
policy_noise: 0.15

# eval
eval_per_rollout: 0.1
eval_steps: null # set with steps per rollout
render: false
render_per_eval: 0.05

curri: {}

# save
cwd: results
rollout_per_save: 0.1