# wandb
wandb: false 
resume_mode: null
load_path: null 
wid: null
project: TD3_debug 
name: hello

# seed 
random_seed: 0

# replay
her_rate: 0.8
her_decay: 0.5
random_relabel_rate: 1.0
if_use_per: false
buffer_size: 1000
dropout_early_termin: false

# env_params
env_name: 'FrankaPNP-v0'
env_params: null
env_kwargs:
  num_envs: 1
  num_robots: 2
  num_cameras: 1
  num_goals: 2
  headless: true
  base_steps: 25
  table_gap: 0.2
  os_rate: 0.8
reward_scale: 1
extra_info_dim: 0 # extra info get from agent

# network
act_net: Actor
critic_net: CriticTwin
net_dim: 256
net_layer: 4
shared_net_layer: 2
net_type: deepset
if_act_target: true 
if_cri_target: true 
gpu_id: 0

# algorithm
agent_name: AgentTD3
max_collect_steps: !!float 1e9
reuse: 1
steps_per_rollout: 40
updates_per_rollout: null # calulate with reuse
batch_size: 200
gamma: 0.98
lr: 0.00024
soft_update_tau: 0.005
explore_noise: 0.2
# TD3
update_freq: 2
policy_noise: 0.15
policy_update_gap: 1

# eval
eval_per_rollout: 1
eval_steps: 4000 # set with steps per rollout
render: true
render_per_eval: 1

curri: {}

# save
cwd: results
rollout_per_save: 0.1