table_gap: # env properties
  init: 0.3
  now: 0.30 
  end: 0.30
  step: 0.00
  indicator: results.handover_1_2_success_rate 
  bar: 0.3 # reward bar to change curriculum
os_rate: 
  init: 0.0
  now: 0.0
  end: 0.8
  step: 0.0
  indicator: results.handover_0_1_success_rate
  bar: 0.7
current_num_goals:
  init: 8
  now: 8
  end: 8
  step: 0.0
  indicator: results.handover_1_1_success_rate 
  bar: 0.9