table_gap: # env properties
  now: 0
  end: 0.2
  step: 0.05
  indicator: (results.handover1_success_rate+results.handover2_success_rate)/2
  bar: 0.7 # reward bar to change curriculum
os_rate: 
  now: 0.2
  end: 0.8
  step: 0.3
  indicator: results.handover0_success_rate
  bar: 0.7 