current_num_goals:
  init: 4
  now: 4
  end: 6
  step: 0.1001
  indicator: handover_success_rate[0,1:].mean().item() 
  bar: 0.7
table_gap: # env properties
  init: 0.3
  now: 0.3
  end: 0.3
  step: 0.05
  indicator: results.handover_1_2_success_rate 
  bar: 0.3 # reward bar to change curriculum