num_envs: 1 # recommend: 1024 (too many env will cause longer update interval and hurt sample effiency)
num_robots: 2
num_goals: 2
os_rate: 0.5
inhand_rate: 0.2 # init obj in hand
headless: false

table_gap: 0.3
goal_space: [0.3, 0.3, 0.2]
robot_gap: 0.7

rand_table_gap: 0.0
control_freq_inv: 10
max_vel: 2
max_grip_vel: 0.1
filter_param: 0.4