num_envs: 1 # recommend: 1024 (too many env will cause longer update interval and hurt sample effiency)
num_robots: 2
num_goals: 1
os_rate: 0.5
inhand_rate: 0.2 # init obj in hand
headless: true

table_gap: 0.3