num_envs: 1024 # recommend: 1024 (too many env will cause longer update interval and hurt sample effiency)
num_robots: 2
num_goals: 1
os_rate: 0.2
table_gap: 0.0
inhand_rate: 0.3 # init obj in hand
robot_gap: 0.7
goal_space: [0.4,0.4,0.2]
table_size: [1.0, 1.0, 0.4]
base_steps: 80
early_termin_step: 40
max_ag_unmoved_steps: 20