num_envs: 1024 # recommend: 1024 (too many env will cause longer update interval and hurt sample effiency)
num_robots: 2
num_goals: 2
inhand_rate: 0.2 # init obj in hand
rand_table_gap: 0.2
max_table_gap: 0.2