num_envs: 1024 # recommend: 1024 (too many env will cause longer update interval and hurt sample effiency)
num_robots: 2
num_goals: 3
os_rate: 0.2
table_gap: 0.0
inhand_rate: 0.2 # init obj in hand

rand_table_gap: 0.0
control_freq_inv: 10
max_vel: 2
filter_param: 0.5