num_goals: 4
current_num_goals: 4
num_robots: 2
os_rate: 0.8
num_envs: 256
num_cameras: 4
extra_goal_sample: 50
max_sample_time: 500
render_size: [640, 400]

# disable early termination
early_termin_step: 100000