num_goals: 8
current_num_goals: 8
num_robots: 2
inhand_rate: 0.0
os_rate: 0.8
num_envs: 256
num_cameras: 4
extra_goal_sample: 50
max_sample_time: 500
obj_sample_mode: task_distri
task_distri: [0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.12]
render_size: [640, 400]

# disable early termination
# early_termin_step: 100000