# @package _global_

wandb: true
project: handover2
name: 8kenv_default_resume
resume_mode: restart
wid: 1j040lfc
entity: jc-bao
load_tag: best

her_rate: 0.8

render: true 

env: 
  num_envs: 8192
  num_robots: 2
  num_goals: 2
  os_rate: 0.95
  table_gap: 0.2
  inhand_rate: 0.2 # init obj in hand

curri:
  table_gap: # env properties
    now: 0.2
    end: 0.2
    step: 0.05
    indicator: '1'
    bar: 0.7 # reward bar to change curriculum
  os_rate: 
    now: 0.95
    end: 0.95
    step: 0.2
    indicator: '1'
    bar: 0.7
  goal_scale: 
    now: 1
    end: 1
    step: 0.2
    indicator: '1'
    bar: 0.7